package com.example.authdemo

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.widget.Button
import android.widget.Toast
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.firebase.auth.FirebaseAuth

class HomeActivity : AppCompatActivity() {
    private lateinit var logoutButton: Button
    private lateinit var GoogleSignInClient: GoogleSignInClient
    private lateinit var authCommon: FirebaseAuth

    override fun onCreate(savedInstanceState: Bundle?){
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_home)

        logoutButton = findViewById(R.id.btnLogout)
        authCommon = FirebaseAuth.getInstance()

        try {
            authCommon.useEmulator("10.0.2.2", 9099)
        } catch (e: Exception) {
            Log.d("Emulator Use Failed", "Cant use the emulator", e)
        }

        logoutButton.setOnClickListener {
            logout()
        }
    }

    fun logout() {
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id)) // Auto-generated by google-services.json
            .requestEmail()
            .build()

        GoogleSignInClient = GoogleSignIn.getClient(this, gso)

        authCommon.signOut()

        GoogleSignInClient.signOut().addOnCompleteListener(this) {
            Toast.makeText(this, "Logged Out", Toast.LENGTH_SHORT).show()
            val intent = Intent(this, LoginActivity::class.java)
            intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
            startActivity(intent)
            finish()
        }
    }
}