package com.example.authdemo

import android.content.Intent
import android.os.Bundle
import android.util.Log
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.ProgressBar
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInClient
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.Firebase
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.FirebaseFirestoreSettings
import com.google.firebase.functions.FirebaseFunctions
import com.google.firebase.functions.functions
import com.google.firebase.firestore.firestore
class LoginActivity : AppCompatActivity() {

    private lateinit var functions: FirebaseFunctions
    private lateinit var etEmail: EditText
    private lateinit var progressBar: ProgressBar
    private lateinit var btnGoogleSignIn: Button
    private lateinit var btnGetCode: Button
    private lateinit var authGoogle: FirebaseAuth
    private lateinit var googleSignInClient: GoogleSignInClient

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_login)

        functions = FirebaseFunctions.getInstance()
        authGoogle = FirebaseAuth.getInstance()
        etEmail = findViewById(R.id.etEmail)
        progressBar = findViewById(R.id.progressBar)
        btnGoogleSignIn = findViewById(R.id.btnGoogle)
        btnGetCode = findViewById(R.id.btnGetCode)

        // --- CONNECT TO EMULATOR ---
        // 10.0.2.2 is the special IP for "localhost" from inside Android Emulator
        try {
            authGoogle.useEmulator("10.0.2.2",9099)
            functions.useEmulator("10.0.2.2", 5001)
        } catch (e: Exception) {
            Log.d("Emulator Use Failed", "Cant use the emulator", e)
        }

        setupGoogleSignIn()

        btnGetCode.setOnClickListener {
            val email = etEmail.text.toString().trim()
            if (email.isNotEmpty()) {
                sendOtp(email)
            } else {
                etEmail.error = "Email is required"
            }
        }
    }

    private fun setupGoogleSignIn() {
        // Configure Google Sign In
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(getString(R.string.default_web_client_id)) // Auto-generated by google-services.json
            .requestEmail()
            .build()

        googleSignInClient = GoogleSignIn.getClient(this, gso)

        val launcher = registerForActivityResult(ActivityResultContracts.StartActivityForResult()) { result ->
            val task = GoogleSignIn.getSignedInAccountFromIntent(result.data)
            try {
                val account = task.getResult(ApiException::class.java)
                firebaseAuthWithGoogle(account.idToken!!)
            } catch (e: ApiException) {
                Log.e("GoogleAuth", "Google Sign In Failed. Code: ${e.statusCode}", e)
                Toast.makeText(this, "Google Error: ${e.statusCode}", Toast.LENGTH_LONG).show()
                Log.w("Auth", "Google sign in failed", e)
            }
        }

        btnGoogleSignIn.setOnClickListener {
            launcher.launch(googleSignInClient.signInIntent)
        }
    }

    private fun firebaseAuthWithGoogle(idToken: String) {
        showLoading(true)
        val credential = GoogleAuthProvider.getCredential(idToken, null)
        authGoogle.signInWithCredential(credential)
            .addOnCompleteListener(this) { task ->
                showLoading(false)
                if (task.isSuccessful) {
                    navigateToHome()
                } else {
                    Toast.makeText(this, "Auth Failed.", Toast.LENGTH_SHORT).show()
                }
            }
    }

    private fun sendOtp(email: String) {
        showLoading(true)

        val data = hashMapOf("email" to email)

        functions.getHttpsCallable("sendEmailOTP")
            .call(data)
            .addOnSuccessListener {
                showLoading(false)
                // SUCCESS: Move to next screen
                Toast.makeText(this, "OTP Sent!", Toast.LENGTH_SHORT).show()
                val intent = Intent(this, OtpActivity::class.java)
                intent.putExtra("USER_EMAIL", email) // Pass the email to the next page
                startActivity(intent)
            }
            .addOnFailureListener { e ->
                showLoading(false)
                Toast.makeText(this, "Failed: ${e.message}", Toast.LENGTH_LONG).show()
                Log.d("OTP", "$e")
            }
    }

    private fun navigateToHome() {
        Toast.makeText(this, "Login Successful!", Toast.LENGTH_SHORT).show()
        val intent = Intent(this, HomeActivity::class.java)
        // Clear back stack so they can't go back to Login
        intent.flags = Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK
        startActivity(intent)
        finish()
    }

    private fun showLoading(isLoading: Boolean) {
        progressBar.visibility = if (isLoading) View.VISIBLE else View.GONE
        findViewById<Button>(R.id.btnGetCode).isEnabled = !isLoading
    }
}